### ISSUE TITLE
Use a stack rather than function for strongly connected components

### ISSUE THREAD

**Issue by Yomguithereal** [graphology/graphology-components#6]

**Comment by luccitan** [comment]
I have been trying to implement a stack version, which is tough.
A version is available [there](https://github.com/luccitan/graphology-components/blob/stack/index.js#L148-L237).

Though, the bench script is showing a loss of performance  : 

```js
100000 executions of the function recursion implementation, in 4951 ms
100000 executions of the stack recursion implementation, in 6556 ms
	-> Execution time difference : 32.42%
```

The difference is even higher on a pseudo-random graph with ~10k nodes (generated from Gephi).
It raises up to 890% difference, with the same script.
(The difference is computed on the sum of executions time).

Run under Node v7.4, V8 may be more efficient with one recursive function than with a recursion stack.

**Comment by Yomguithereal** [comment]
I am currently trying to pinpoint the performance bottleneck in those functions and I feel the `Set` is somewhat to blame. But let me check this more thoroughly.

**Comment by Yomguithereal** [comment]
Nope. That's not it...

**Comment by Yomguithereal** [comment]
Ok, there is something weird with the stack. Investigating...
